### ISSUE TITLE
Suggestion to use default mysql server engine

### ISSUE THREAD

**Issue by jeanpaulgalea** [sndrsmnk/ng-rddmarc#1]
Hello,

Thank you for open sourcing this.

Just a minor suggestion to consider removing ENGINE=MyISAM from the CREATE statements. Most people will probably want to use InnoDB, which is the default in newer MySQL releases.

**Comment by sndrsmnk** [comment]
Sure. Sounds sane. I've removed the ENGINE=MyISAM from the SQL create statements!
Thanks!
