### ISSUE TITLE
Already have google.com's report id

### ISSUE THREAD

**Issue by Julian0815** [sndrsmnk/ng-rddmarc#3]
It seems that I get reports multiple times from google.
I don't know why and how to handle them correctly.
The output of ng-rddmarc is:

Parsing /var/mail/.../dmarc_rua/new/1521423324.M595838P2811....
Already have google.com's report id 12212373041187910978 as serial 244, skipped
[...]

I'm using ng-rddmarc to parse a maildir every 6 hours

**Comment by sndrsmnk** [comment]
I see the same on my setups from time to time but it's not something this script can fix though.
Google should look into the duplicate reports, they really are identical.

Currently ng-rddmarc will leave that message where it was for the sysadmin to check it out.

Either run with the -r(eplace duplicates) option or tell me what you want to see happen to messages containing duplicate report IDs.

**Comment by Julian0815** [comment]
Using -r is completely fine for me. I didn't knew that this is a known issue.
